# Generated by Django 4.0.6 on 2022-07-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_shroom_user_alter_shroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shroom',
            name='picking_season',
            field=models.CharField(choices=[('SUM', 'Summer'), ('SPG', 'Spring'), ('FLL', 'Fall'), ('WIN', 'Winter'), ('NAN', 'None')], default='SUM', max_length=3),
        ),
    ]
